package com.yanwu.demo.saga.client.dao.model;

import java.io.Serializable;

public class DemoClientEntity implements Serializable {
    /**
     * <pre>
     *
     * 表字段 : demo_client.client_id
     * </pre>
     */
    private Integer clientId;

    /**
     * <pre>
     *
     * 表字段 : demo_client.client_name
     * </pre>
     */
    private String clientName;

    /**
     * <pre>
     *
     * 表字段 : demo_client.client_password
     * </pre>
     */
    private String clientPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo_client
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 获取：
     * 表字段：demo_client.client_id
     * </pre>
     *
     * @return demo_client.client_id：
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：demo_client.client_id
     * </pre>
     *
     * @param clientId demo_client.client_id：
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * <pre>
     * 获取：
     * 表字段：demo_client.client_name
     * </pre>
     *
     * @return demo_client.client_name：
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：demo_client.client_name
     * </pre>
     *
     * @param clientName demo_client.client_name：
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * <pre>
     * 获取：
     * 表字段：demo_client.client_password
     * </pre>
     *
     * @return demo_client.client_password：
     */
    public String getClientPassword() {
        return clientPassword;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：demo_client.client_password
     * </pre>
     *
     * @param clientPassword demo_client.client_password：
     */
    public void setClientPassword(String clientPassword) {
        this.clientPassword = clientPassword == null ? null : clientPassword.trim();
    }
}